baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tuna Linux'
theme = 'tunalinux'
sectionPagesMenu = "main"

[menu]

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "news"
url = "/news/"
weight = 2

[[menu.main]]
name = "packages"
url = "/packages/"
weight = 3

[[menu.main]]
name = "about"
url = "/about/"
weight = 4

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

[markup.tableOfContents]
startLevel = 2
endLevel   = 3
ordered    = true

[privacy]

[privacy.vimeo]
disabled = false
simple   = true

[privacy.twitter]
disabled  = false
enableDNT = true
simple    = true

[privacy.instagram]
disabled = false
simple   = true

[privacy.youtube]
disabled        = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
