baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tuna Linux'
theme = 'tunalinux'

[menu]

[[menu.main]]
identifier = "news"
name = "news"
url = "/news/"
weight = 1

[[menu.main]]
identifier = "packages"
name = "packages"
url = "/packages/"
weight = 2

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

[markup.tableOfContents]
startLevel = 2
endLevel   = 3
ordered    = true

[privacy]

[privacy.vimeo]
disabled = false
simple   = true

[privacy.twitter]
disabled  = false
enableDNT = true
simple    = true

[privacy.instagram]
disabled = false
simple   = true

[privacy.youtube]
disabled        = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
